language: php

branches:
  only:
    - master
    - dev

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

install:
  - composer self-update
  - composer install -n --prefer-source

script:
  - vendor/bin/phpcs --standard=./phpcs.xml -sv --encoding=utf-8 ./src/app/code
